services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./front/dist:/var/www/html
      - ./api:/var/www
      # FROM HOST
      - /etc/letsencrypt/live/cream-fm.art:/etc/letsencrypt/live/cream-fm.art
    networks:
      - internal
    depends_on:
      - api
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    # command: "tail -f /dev/null" # Keep the container running

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # entrypoint: "tail -f /dev/null" # Keep the container running

  frontend-builder:
    build:
      context: ./front
      dockerfile: ./Dockerfile-build
    volumes:
      - ./front:/app
      - ./front/dist:/app/dist

  api-taskserver:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.prod
    container_name: api-taskserver
    hostname: api-taskserver
    ports:
      - "8001:8000"
    expose:
      - "8000"
      - "5174"
    networks:
      - internal
    volumes:
      - ./api:/var/www
    entrypoint: /bin/sh -c "php artisan queue:work"
    depends_on:
      - postgres-db
      - redis
      - storage
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - SCOUT_DRIVER=${SCOUT_DRIVER}
      - MEILISEARCH_HOST=${MEILISEARCH_HOST}
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_URL=${AWS_URL}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - FILESYSTEM_PUBLIC_DRIVER=${FILESYSTEM_PUBLIC_DRIVER}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - SERVER_NAME=${SERVER_NAME}
      - OCTANE_SERVER=${OCTANE_SERVER}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - APP_ENV=${APP_ENV}

  api-scout-runner:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.prod
    container_name: api-scout-runner
    hostname: api-scout-runner
    ports:
      - "8002:8000"
    expose:
      - "8000"
      - "5174"
    volumes:
      - ./api:/var/www
    entrypoint: /bin/sh -c "php artisan queue:work --queue=scout"
    networks:
      - internal
    depends_on:
      - postgres-db
      - redis
      - storage
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - SCOUT_DRIVER=${SCOUT_DRIVER}
      - MEILISEARCH_HOST=${MEILISEARCH_HOST}
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_URL=${AWS_URL}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - FILESYSTEM_PUBLIC_DRIVER=${FILESYSTEM_PUBLIC_DRIVER}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - SERVER_NAME=${SERVER_NAME}
      - OCTANE_SERVER=${OCTANE_SERVER}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}

  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.prod
    container_name: api
    hostname: api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./api:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
      - ./liq/configs:/var/liq/example # for liq config
    networks:
      - internal
    depends_on:
      - postgres-db
      - redis
      - storage
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_URL=${AWS_URL}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - FILESYSTEM_PUBLIC_DRIVER=${FILESYSTEM_PUBLIC_DRIVER}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - SERVER_NAME=${SERVER_NAME}
      - OCTANE_SERVER=${OCTANE_SERVER}
      - APP_ENV=${APP_ENV}

  postgres-db:
    container_name: postgres-db
    hostname: postgres-db
    image: "postgres:17-alpine"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - internal
    ports:
      - "5432:5432"

  storage:
    image: minio/minio
    container_name: storage
    hostname: storage
    ports:
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_REGION=${MINIO_REGION}
    networks:
      - internal
    volumes:
      - ./storage-data:/data
    command: server --address :9001 /data

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - internal
    user: redis

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    hostname: meilisearch
    ports:
      - 7700:7700
    networks:
      - internal

  tg-bot:
    container_name: tg-bot
    hostname: tg-bot
    ports:
      - 3005:3000
    volumes:
      - ./tg:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_APP_URL=${WEB_APP_URL}
      - API_URL=${API_URL}
    # depends_on:
    #   - api
    build:
      context: ./tg
      dockerfile: ./docker/Dockerfile-dev
    networks:
      - internal

  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://storage:9001 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      if ! /usr/bin/mc ls myminio | grep -q 'killme'; then
        echo 'Creating bucket killme...';
        /usr/bin/mc mb myminio/killme;
        /usr/bin/mc anonymous set public myminio/killme;
      else
        echo 'Bucket killme already exists, skipping creation.';
      fi;
      exit 0;
      "
    networks:
      - internal

volumes:
  postgres_data:

networks:
  # traefik-proxy:
  #   name: traefik-proxy
  internal:
    name: internal
